"use strict";
AFRAME.registerComponent("gallery", { schema: {
		exhibits: {type: "array"}, // array of IDs of images
		metafile: {type: "asset"}, // metadata file generated by annotator
		mapfile:  {type: "map"}, // 
		navtools: {type: "selectorAll"}
	},
	toolState: 0, //0=no tool, 1=have tool, 2=is portal
	activeTool: null,
	zones: null,
	greeting:
		"Welcome to the Gallery!\n\n"+
		"You need a controller.\n"+
		"Pick up the entry portal to\n"+
		"begin. It's at your feet.\n"+
		"Put it on your face.",
	init: function() {
		// SCOPES ARE ANNOYING
		var data = this.data;
		var self = this;
		// GREET USER
		var greeting = document.createElement("p");
		greeting.innerHTML = (this.greeting);
		greeting.style.width = "25vw";
		greeting.style.zIndex = 999;
		greeting.style.position = "relative";
		greeting.style.left = "5em";
		greeting.style.background = "white";
		greeting.style.padding = "2em";
		setTimeout(function() {
			document.querySelector('.a-enter-vr').appendChild(greeting);
		}, 1000);

		// LOAD METADATA
		var metafile = document.querySelector('a-asset-item[src="' + data.metafile +'"]').data;
		this.zones = JSON.parse(metafile);

		// REGISTER MAP TOOL LISTENERS
		for(var i = 0; i < data.navtools.length; i++) {
			var tool = data.navtools[i];
			tool.addEventListener('click', function(e) {
				console.log("Clicked", e);
				if(self.toolState == 0) { // Picked up!
					//tool.setAttribute("src", "temp/out.jpg");
					var cursor = e.detail.cursorEl;
					if(cursor.hasAttribute("cursor")) { // Workaround for 2D debug
						cursor.parentElement.parentElement.appendChild(tool);
					} else {
						cursor.appendChild(tool);
					}
					self.toolState = 1;
					return;
				}
				if(self.zones && self.toolstate == 1) { // Selected a zone!
					var zones = self.zones;
					var isect = e.detail.intersection.uv;
					for(var i = 0; i < zones.length; i++) {
						var coords = zones[i].coords;
						if(coords[0] < isect.x && coords[2] > isect.x &&
							coords[1] < isect.y && coords[3] > isect.y) {
							console.log(zones[i].name);
							//target.setAttribute("src", "temp/flipped."+zones[i].name);
							self.toolState = 2; // transition to portal mode
						}
					}
				}
			});
		}

	}
});

